export const colors = {
  background: '$background',
  surface: '$surface',
  surface1: '$surface1',
  surface2: '$surface2',
  surface3: '$surface3',
  surface4: '$surface4',
  content: '$content',
  contentSecondary: '$contentSecondary',
  contentInverse: '$contentInverse',
  outline: '$outline',
  outlineVariant: '$outlineVariant',
  accent: '$accent',
  accentHover: '$accentHover',
  accentContainer: '$accentContainer',
  primary: '$primary',
  primaryContainer: '$primaryContainer',
  destructive: '$destructive',
  destructiveContainer: '$destructiveContainer',
  success: '$success',
  successContainer: '#dcfce7',
  warning: '$warning',
  warningContainer: '#fef3c7',
  inverseSurface: '$inverseSurface',
  white: '$white',
  black: '$black',
  transparent: '$transparent',
} as const
