import { ensureEnv } from '@take-out/helpers'

if (typeof window !== 'undefined') {
  throw new Error(`This is a server-only file`)
}

// 🔒 start - this is generated by "bun env:update"
export const BETTER_AUTH_SECRET = ensureEnv('BETTER_AUTH_SECRET')
export const BETTER_AUTH_URL = ensureEnv('BETTER_AUTH_URL')
export const ONE_SERVER_URL = ensureEnv('ONE_SERVER_URL')
export const OPENROUTER_API_KEY = ensureEnv('OPENROUTER_API_KEY', '')
export const OPENROUTER_MODEL = ensureEnv('OPENROUTER_MODEL', 'openrouter/free')
export const CHAT_QUOTA_SECRET = ensureEnv('CHAT_QUOTA_SECRET', '')
export const VITE_WEB_HOSTNAME = ensureEnv('VITE_WEB_HOSTNAME', '')
export const DATABASE_URL = ensureEnv('DATABASE_URL').replace(
  /([?&])sslmode=(?:prefer|require|verify-ca)(?=&|$)/,
  '$1sslmode=verify-full',
)
export const ADMIN_USERNAME = ensureEnv('ADMIN_USERNAME', '')
export const ADMIN_PASSWORD = ensureEnv('ADMIN_PASSWORD', '')
export const CLOUDFLARE_R2_ENDPOINT = ensureEnv('CLOUDFLARE_R2_ENDPOINT', '')
export const CLOUDFLARE_R2_ACCESS_KEY = ensureEnv('CLOUDFLARE_R2_ACCESS_KEY', '')
export const CLOUDFLARE_R2_SECRET_KEY = ensureEnv('CLOUDFLARE_R2_SECRET_KEY', '')
export const CLOUDFLARE_R2_BUCKET = ensureEnv('CLOUDFLARE_R2_BUCKET', '')
export const OPENROUTER_EMBEDDING_MODEL = ensureEnv(
  'OPENROUTER_EMBEDDING_MODEL',
  'nvidia/nemotron-3-embed-1b:free',
)
// 🔒 end - this is generated by "bun env:update"
